server:
  servlet:
    encoding:
      force: true
      charset: UTF-8

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDS_IP}:3306/savegame?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# HS512알고리즘, 64byte 이상 secret key 사용
# zerobase-backend-frontend-everyone-success-savegame-challenge-application-find-goodjob-we-can-do-it-good-life
jwt:
  secret: emVyb2Jhc2UtYmFja2VuZC1mcm9udGVuZC1ldmVyeW9uZS1zdWNjZXNzLXNhdmVnYW1lLWNoYWxsZW5nZS1hcHBsaWNhdGlvbi1maW5kLWdvb2Rqb2Itd2UtY2FuLWRvLWl0LWdvb2QtbGlmZQ==

kakao:
  rest-api-key: ${KAKAO_RESTAPIKEY}