server:
  servlet:
    encoding:
      force: true
      charset: UTF-8

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/greenbook?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    username: ${LOCAL_MYSQL_USERNAME}
    password: ${LOCAL_MYSQL_PASSWORD}
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database: mysql
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: 127.0.0.1
    port: 6379

## HS512알고리즘, 64byte 이상 secret key 사용
## zerobase-backend-frontend-everyone-success-savegame-challenge-application-find-goodjob-we-can-do-it-good-life
#jwt:
#  header: Authorization
#  secret: emVyb2Jhc2UtYmFja2VuZC1mcm9udGVuZC1ldmVyeW9uZS1zdWNjZXNzLXNhdmVnYW1lLWNoYWxsZW5nZS1hcHBsaWNhdGlvbi1maW5kLWdvb2Rqb2Itd2UtY2FuLWRvLWl0LWdvb2QtbGlmZQ==
#  token-validity-in-seconds: 86400
#  refresh-token-validity-in-seconds: 604800

kakao:
  authUrl: https://kauth.kakao.com/oauth/token
  userApiUrl: https://kapi.kakao.com/v2/user/me
  restapiKey: c6a261701200c2e34deb814d46337935
  redirectUrl: http://localhost:8080/callback